def serialize_snapshot(world_model):
    return {
        "price": world_model.get("price"),
        "direction": world_model.get("direction"),
        "sentiment_label": world_model.get("sentiment_label"),
        "sentiment_score": world_model.get("sentiment_score"),
        "state_label": world_model.get("state_label"),
        "continuation_score": world_model.get("continuation_score"),
        "shock_score": world_model.get("shock_score"),
        "confidence": world_model.get("confidence"),
        "model_version": world_model.get("model_version"),
        "confidence_score": world_model.get("confidence_score"),
        "confidence_components": world_model.get("confidence_components") or {},
        "data_quality": world_model.get("data_quality") or {},
        "transition_probs": world_model.get("transition_probs") or [],
        "expected_returns": world_model.get("expected_returns") or {},
        "market_context": world_model.get("market_context") or {},
        "targets": {
            "upside": world_model.get("upside_targets") or [],
            "downside": world_model.get("downside_targets") or [],
            "invalidation": world_model.get("invalidation") or {},
        },
        "invalidation_price": world_model.get("invalidation_price"),
        "invalidation_reason": world_model.get("invalidation_reason") or "",
        "evidence": world_model.get("evidence") or [],
        "last_updated": world_model.get("last_updated_display"),
        "data_warning": world_model.get("data_warning") or "",
    }
