def serialize_snapshot(world_model):
    return {
        "price": world_model.get("price"),
        "direction": world_model.get("direction"),
        "sentiment_label": world_model.get("sentiment_label"),
        "sentiment_score": world_model.get("sentiment_score"),
        "state_label": world_model.get("state_label"),
        "primary_scenario": world_model.get("primary_scenario"),
        "counter_scenario": world_model.get("counter_scenario"),
        "scenario_label": world_model.get("scenario_label"),
        "trend_score": world_model.get("trend_score"),
        "reversal_risk_score": world_model.get("reversal_risk_score"),
        "rebound_improvement_score": world_model.get("rebound_improvement_score"),
        "continuation_score": world_model.get("continuation_score"),
        "shock_score": world_model.get("shock_score"),
        "confidence": world_model.get("confidence"),
        "model_version": world_model.get("model_version"),
        "confidence_score": world_model.get("confidence_score"),
        "confidence_components": world_model.get("confidence_components") or {},
        "data_quality": world_model.get("data_quality") or {},
        "readiness": world_model.get("readiness") or {},
        "readiness_level": world_model.get("readiness_level"),
        "directional_allowed": world_model.get("directional_allowed"),
        "transition_probs": world_model.get("transition_probs") or [],
        "expected_returns": world_model.get("expected_returns") or {},
        "intermarket_technicals": world_model.get("intermarket_technicals") or {},
        "basecalc_signal": world_model.get("basecalc_signal") or {},
        "targets": {
            "upside": world_model.get("upside_targets") or [],
            "downside": world_model.get("downside_targets") or [],
            "near_levels": world_model.get("near_levels") or {},
            "target_ranges": world_model.get("target_ranges") or [],
            "invalidation": world_model.get("invalidation") or {},
        },
        "invalidation_price": world_model.get("invalidation_price"),
        "invalidation_reason": world_model.get("invalidation_reason") or "",
        "evidence": world_model.get("evidence") or [],
        "last_updated": world_model.get("last_updated_display"),
        "data_warning": world_model.get("data_warning") or "",
    }
