# Generated by Django 4.2.20 on 2025-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('summary', models.TextField(blank=True, verbose_name='要約')),
                ('content', models.TextField(verbose_name='分析内容')),
                ('analysis_date', models.DateField(verbose_name='分析日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'AI分析結果',
                'verbose_name_plural': 'AI分析結果',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
