# Generated by Codex on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("symbol", models.CharField(max_length=32)),
                ("price", models.FloatField()),
                ("open", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                ("low", models.FloatField(blank=True, null=True)),
                ("close", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("timeframe", models.CharField(max_length=16)),
                ("source", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="WorldModelPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField()),
                ("state_key", models.CharField(max_length=64)),
                ("state_label", models.CharField(max_length=64)),
                ("direction", models.CharField(max_length=16)),
                ("sentiment_score", models.IntegerField()),
                ("continuation_score", models.IntegerField()),
                ("shock_score", models.IntegerField()),
                ("confidence", models.CharField(max_length=16)),
                ("main_scenario", models.TextField()),
                ("sub_scenario", models.TextField(blank=True)),
                ("invalidation_price", models.FloatField(blank=True, null=True)),
                ("upside_targets", models.JSONField(default=list)),
                ("downside_targets", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=list)),
                ("features", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ema5", models.FloatField(blank=True, null=True)),
                ("ema20", models.FloatField(blank=True, null=True)),
                ("ema60", models.FloatField(blank=True, null=True)),
                ("vwap", models.FloatField(blank=True, null=True)),
                ("rsi14", models.FloatField(blank=True, null=True)),
                ("macd", models.FloatField(blank=True, null=True)),
                ("macd_signal", models.FloatField(blank=True, null=True)),
                ("adx14", models.FloatField(blank=True, null=True)),
                ("atr14", models.FloatField(blank=True, null=True)),
                ("bb_upper", models.FloatField(blank=True, null=True)),
                ("bb_mid", models.FloatField(blank=True, null=True)),
                ("bb_lower", models.FloatField(blank=True, null=True)),
                (
                    "market_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basecalc.marketsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horizon", models.CharField(max_length=16)),
                ("evaluated_at", models.DateTimeField()),
                ("price_at_evaluation", models.FloatField()),
                ("realized_return_pct", models.FloatField()),
                ("direction_hit", models.BooleanField()),
                ("upside_t1_hit", models.BooleanField(default=False)),
                ("upside_t2_hit", models.BooleanField(default=False)),
                ("downside_t1_hit", models.BooleanField(default=False)),
                ("downside_t2_hit", models.BooleanField(default=False)),
                ("invalidation_hit", models.BooleanField(default=False)),
                ("mfe_pct", models.FloatField(blank=True, null=True)),
                ("mae_pct", models.FloatField(blank=True, null=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basecalc.worldmodelprediction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="marketsnapshot",
            index=models.Index(
                fields=["symbol", "-created_at"],
                name="basecalc_ma_symbol_bc12d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketsnapshot",
            index=models.Index(
                fields=["timeframe", "-created_at"],
                name="basecalc_ma_timefra_7dd648_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="worldmodelprediction",
            index=models.Index(fields=["-created_at"], name="basecalc_wo_created_e95737_idx"),
        ),
        migrations.AddIndex(
            model_name="worldmodelprediction",
            index=models.Index(
                fields=["state_key", "-created_at"],
                name="basecalc_wo_state_k_3b441a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="worldmodelprediction",
            index=models.Index(
                fields=["direction", "-created_at"],
                name="basecalc_wo_directi_8be147_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="technicalsnapshot",
            index=models.Index(fields=["-created_at"], name="basecalc_te_created_93de3f_idx"),
        ),
        migrations.AddConstraint(
            model_name="predictionoutcome",
            constraint=models.UniqueConstraint(
                fields=("prediction", "horizon"),
                name="unique_basecalc_prediction_horizon",
            ),
        ),
        migrations.AddIndex(
            model_name="predictionoutcome",
            index=models.Index(
                fields=["horizon", "-evaluated_at"],
                name="basecalc_pr_horizon_1981a5_idx",
            ),
        ),
    ]
