# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basecalc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("symbol", models.CharField(max_length=32)),
                ("timeframe", models.CharField(max_length=16)),
                ("timestamp", models.DateTimeField()),
                ("open", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                ("low", models.FloatField(blank=True, null=True)),
                ("close", models.FloatField()),
                ("volume", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(max_length=64)),
            ],
        ),
        migrations.AddConstraint(
            model_name="marketbar",
            constraint=models.UniqueConstraint(
                fields=("symbol", "timeframe", "timestamp"),
                name="unique_basecalc_market_bar",
            ),
        ),
        migrations.AddIndex(
            model_name="marketbar",
            index=models.Index(
                fields=["symbol", "timeframe", "timestamp"],
                name="basecalc_ma_symbol_bf4cf8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketbar",
            index=models.Index(
                fields=["timeframe", "-timestamp"],
                name="basecalc_ma_timefra_a4436d_idx",
            ),
        ),
    ]
