# Generated by Django 4.2.20 on 2025-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('macro', 'Macroeconomics'), ('stock', 'Stock Market')], max_length=10)),
                ('score', models.IntegerField(default=3, help_text='1 (Bearish) to 5 (Bullish)')),
            ],
        ),
    ]
