# Generated by Django 4.2.20 on 2025-12-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analyst',
        ),
    ]
