# Generated by Django 4.2.19 on 2026-05-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fred_series_id', models.CharField(max_length=64, unique=True)),
                ('name_ja', models.CharField(max_length=128)),
                ('name_en', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(choices=[('inflation', 'インフレ'), ('employment', '雇用・労働'), ('growth', '景気・成長'), ('rates', '金利・通貨'), ('market', '市場ストレス')], max_length=16)),
                ('importance', models.CharField(choices=[('A', 'A（必須）'), ('B', 'B（重要）'), ('C', 'C（参考）')], default='B', max_length=1)),
                ('frequency', models.CharField(choices=[('daily', '日次'), ('weekly', '週次'), ('monthly', '月次'), ('quarterly', '四半期')], default='monthly', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'fred_series_id'],
            },
        ),
        migrations.CreateModel(
            name='RegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('regime_label', models.CharField(choices=[('expansion', '拡大'), ('slowdown', '減速'), ('contraction', '縮小'), ('recovery', '回復'), ('unknown', '判定不能')], default='unknown', max_length=16)),
                ('inflation_flag', models.CharField(choices=[('high', '高止まり'), ('easing', '鈍化'), ('normal', '正常'), ('unknown', '判定不能')], default='unknown', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('indicator_vector', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['-snapshot_date'], name='macro_regim_snapsho_e793ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('value', models.FloatField()),
                ('prev_value', models.FloatField(blank=True, null=True)),
                ('yoy_change', models.FloatField(blank=True, null=True)),
                ('deviation_from_long_term', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='macro.indicator')),
            ],
            options={
                'ordering': ['indicator', '-observation_date'],
                'indexes': [models.Index(fields=['indicator', '-observation_date'], name='macro_obser_indicat_5f7124_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('indicator', 'observation_date'), name='uq_indicator_date'),
        ),
    ]
