from django.db import migrations


# 初期登録する FRED 系列。重要度Aは類似度計算と画面の主要表示に使用。
# 注: ISM 製造業/非製造業 PMI は FRED で廃番のため、INDPRO / TCU を代替指標として登録。
INDICATORS = [
    # インフレ
    {
        'fred_series_id': 'CPIAUCSL',
        'name_ja': 'CPI',
        'name_en': 'Consumer Price Index for All Urban Consumers',
        'category': 'inflation',
        'importance': 'A',
        'frequency': 'monthly',
        'unit': 'index',
        'description': '消費者物価指数。総合インフレの代表指標。',
        'display_order': 10,
    },
    {
        'fred_series_id': 'CPILFESL',
        'name_ja': 'Core CPI',
        'name_en': 'CPI Less Food and Energy',
        'category': 'inflation',
        'importance': 'A',
        'frequency': 'monthly',
        'unit': 'index',
        'description': '食品・エネルギーを除いたコアCPI。基調インフレを把握する指標。',
        'display_order': 20,
    },
    {
        'fred_series_id': 'PCEPI',
        'name_ja': 'PCE',
        'name_en': 'PCE Price Index',
        'category': 'inflation',
        'importance': 'A',
        'frequency': 'monthly',
        'unit': 'index',
        'description': '個人消費支出物価指数。FRBが政策判断で重視する。',
        'display_order': 30,
    },
    {
        'fred_series_id': 'PCEPILFE',
        'name_ja': 'Core PCE',
        'name_en': 'Core PCE Price Index',
        'category': 'inflation',
        'importance': 'A',
        'frequency': 'monthly',
        'unit': 'index',
        'description': 'FRBが最重視するコアインフレ指標。',
        'display_order': 40,
    },
    {
        'fred_series_id': 'T5YIE',
        'name_ja': '5年期待インフレ率',
        'name_en': '5-Year Breakeven Inflation Rate',
        'category': 'inflation',
        'importance': 'B',
        'frequency': 'daily',
        'unit': '%',
        'description': '債券市場が織り込む5年先の期待インフレ率。',
        'display_order': 50,
    },
    # 雇用・労働
    {
        'fred_series_id': 'UNRATE',
        'name_ja': '失業率',
        'name_en': 'Unemployment Rate',
        'category': 'employment',
        'importance': 'A',
        'frequency': 'monthly',
        'unit': '%',
        'description': '労働市場の代表指標。遅行性あり。',
        'display_order': 100,
    },
    {
        'fred_series_id': 'PAYEMS',
        'name_ja': 'NFP（非農業雇用者数）',
        'name_en': 'Total Nonfarm Payrolls',
        'category': 'employment',
        'importance': 'A',
        'frequency': 'monthly',
        'unit': '千人',
        'description': '雇用統計の中心指標。前月差で発表される。',
        'display_order': 110,
    },
    {
        'fred_series_id': 'CES0500000003',
        'name_ja': '平均時給',
        'name_en': 'Average Hourly Earnings',
        'category': 'employment',
        'importance': 'B',
        'frequency': 'monthly',
        'unit': '$',
        'description': '賃金インフレ圧力の指標。',
        'display_order': 120,
    },
    {
        'fred_series_id': 'JTSJOL',
        'name_ja': '求人数（JOLTS）',
        'name_en': 'Job Openings: Total Nonfarm',
        'category': 'employment',
        'importance': 'B',
        'frequency': 'monthly',
        'unit': '千件',
        'description': '労働需給の先行指標。',
        'display_order': 130,
    },
    # 景気・成長
    {
        'fred_series_id': 'GDPC1',
        'name_ja': '実質GDP',
        'name_en': 'Real Gross Domestic Product',
        'category': 'growth',
        'importance': 'A',
        'frequency': 'quarterly',
        'unit': '十億$',
        'description': '景気の最終的な全体指標。四半期発表。',
        'display_order': 200,
    },
    {
        'fred_series_id': 'INDPRO',
        'name_ja': '鉱工業生産指数',
        'name_en': 'Industrial Production Index',
        'category': 'growth',
        'importance': 'A',
        'frequency': 'monthly',
        'unit': 'index',
        'description': '製造業活動の代表指標。ISM廃止のため代替として採用。',
        'display_order': 210,
    },
    {
        'fred_series_id': 'TCU',
        'name_ja': '設備稼働率',
        'name_en': 'Capacity Utilization: Total Industry',
        'category': 'growth',
        'importance': 'B',
        'frequency': 'monthly',
        'unit': '%',
        'description': '生産能力の利用度。需要強度を示す。',
        'display_order': 220,
    },
    {
        'fred_series_id': 'RSAFS',
        'name_ja': '小売売上高',
        'name_en': 'Retail Sales',
        'category': 'growth',
        'importance': 'B',
        'frequency': 'monthly',
        'unit': '百万$',
        'description': '消費の代表指標。',
        'display_order': 230,
    },
    {
        'fred_series_id': 'UMCSENT',
        'name_ja': 'ミシガン消費者信頼感',
        'name_en': 'University of Michigan Consumer Sentiment',
        'category': 'growth',
        'importance': 'B',
        'frequency': 'monthly',
        'unit': 'index',
        'description': '消費者の景気心理を測る代表指標。',
        'display_order': 240,
    },
    {
        'fred_series_id': 'HOUST',
        'name_ja': '住宅着工件数',
        'name_en': 'Housing Starts',
        'category': 'growth',
        'importance': 'C',
        'frequency': 'monthly',
        'unit': '千件',
        'description': '住宅市場の先行指標。金利感応度高い。',
        'display_order': 250,
    },
    # 金利・通貨
    {
        'fred_series_id': 'DFF',
        'name_ja': 'FF金利',
        'name_en': 'Federal Funds Effective Rate',
        'category': 'rates',
        'importance': 'A',
        'frequency': 'daily',
        'unit': '%',
        'description': 'FRBの政策金利。金融環境の起点。',
        'display_order': 300,
    },
    {
        'fred_series_id': 'DGS10',
        'name_ja': '米10年国債利回り',
        'name_en': '10-Year Treasury Constant Maturity Rate',
        'category': 'rates',
        'importance': 'A',
        'frequency': 'daily',
        'unit': '%',
        'description': '長期金利の代表。株式の割引率に直結。',
        'display_order': 310,
    },
    {
        'fred_series_id': 'DGS2',
        'name_ja': '米2年国債利回り',
        'name_en': '2-Year Treasury Constant Maturity Rate',
        'category': 'rates',
        'importance': 'B',
        'frequency': 'daily',
        'unit': '%',
        'description': '短期金利。金融政策見通しを反映。',
        'display_order': 320,
    },
    {
        'fred_series_id': 'T10Y2Y',
        'name_ja': '米2-10年スプレッド',
        'name_en': '10Y-2Y Treasury Spread',
        'category': 'rates',
        'importance': 'A',
        'frequency': 'daily',
        'unit': '%',
        'description': '逆イールド = リセッションの先行指標。',
        'display_order': 330,
    },
    {
        'fred_series_id': 'DTWEXBGS',
        'name_ja': 'ドル指数（広義）',
        'name_en': 'Trade-Weighted U.S. Dollar Index: Broad',
        'category': 'rates',
        'importance': 'B',
        'frequency': 'daily',
        'unit': 'index',
        'description': '通貨ベース・広義のドル強さ。',
        'display_order': 340,
    },
    {
        'fred_series_id': 'DEXJPUS',
        'name_ja': 'USD/JPY',
        'name_en': 'Japanese Yen to U.S. Dollar Exchange Rate',
        'category': 'rates',
        'importance': 'B',
        'frequency': 'daily',
        'unit': 'JPY',
        'description': '日経への影響が大きい為替レート。',
        'display_order': 350,
    },
    # 市場ストレス
    {
        'fred_series_id': 'VIXCLS',
        'name_ja': 'VIX',
        'name_en': 'CBOE Volatility Index',
        'category': 'market',
        'importance': 'B',
        'frequency': 'daily',
        'unit': 'index',
        'description': '株式市場の恐怖指数。リスクオン/オフを示す。',
        'display_order': 400,
    },
    {
        'fred_series_id': 'BAMLH0A0HYM2',
        'name_ja': 'ハイイールド社債スプレッド',
        'name_en': 'ICE BofA US High Yield Index Option-Adjusted Spread',
        'category': 'market',
        'importance': 'B',
        'frequency': 'daily',
        'unit': '%',
        'description': '信用リスク警戒度。広がるとリスクオフ。',
        'display_order': 410,
    },
]


def seed_indicators(apps, schema_editor):
    Indicator = apps.get_model('macro', 'Indicator')
    for entry in INDICATORS:
        Indicator.objects.update_or_create(
            fred_series_id=entry['fred_series_id'],
            defaults={
                'name_ja': entry['name_ja'],
                'name_en': entry['name_en'],
                'category': entry['category'],
                'importance': entry['importance'],
                'frequency': entry['frequency'],
                'unit': entry['unit'],
                'description': entry['description'],
                'display_order': entry['display_order'],
                'is_active': True,
            },
        )


def reverse_seed_indicators(apps, schema_editor):
    Indicator = apps.get_model('macro', 'Indicator')
    series_ids = [entry['fred_series_id'] for entry in INDICATORS]
    Indicator.objects.filter(fred_series_id__in=series_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_indicators, reverse_seed_indicators),
    ]
