# Generated by Django 4.2.19 on 2026-05-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0002_seed_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(choices=[('N225', '日経225'), ('GSPC', 'S&P 500')], max_length=16)),
                ('observation_month', models.DateField()),
                ('close_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker', 'observation_month'],
                'indexes': [models.Index(fields=['ticker', 'observation_month'], name='macro_price_ticker_60725f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.UniqueConstraint(fields=('ticker', 'observation_month'), name='uq_ticker_month'),
        ),
    ]
