# Generated by Django 4.2.19 on 2026-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0005_phase2_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.CharField(choices=[('fred', 'FRED'), ('cboe', 'Cboe'), ('finra', 'FINRA'), ('aaii', 'AAII'), ('naaim', 'NAAIM'), ('yfinance', 'Yahoo Finance')], default='fred', max_length=16),
        ),
    ]
