# Generated by Django 4.2.19 on 2026-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0007_phase4_external_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
