# Generated by Django 4.2.19 on 2026-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0008_dashboardcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
