# Generated by Django 4.2.19 on 2026-05-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0018_world_model_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('observation_date', models.DateField()),
                ('close_price', models.FloatField()),
                ('adjusted_close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='yfinance', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker', 'observation_date'],
            },
        ),
        migrations.CreateModel(
            name='WorldStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(unique=True)),
                ('cadence', models.CharField(choices=[('daily', '日次'), ('weekly', '週次'), ('monthly', '月次'), ('manual', '手動')], default='daily', max_length=16)),
                ('growth_score', models.FloatField(blank=True, null=True)),
                ('labor_score', models.FloatField(blank=True, null=True)),
                ('inflation_score', models.FloatField(blank=True, null=True)),
                ('policy_pressure_score', models.FloatField(blank=True, null=True)),
                ('liquidity_score', models.FloatField(blank=True, null=True)),
                ('credit_score', models.FloatField(blank=True, null=True)),
                ('risk_appetite_score', models.FloatField(blank=True, null=True)),
                ('market_trend_score', models.FloatField(blank=True, null=True)),
                ('external_shock_score', models.FloatField(blank=True, null=True)),
                ('market_stress_score', models.FloatField(blank=True, null=True)),
                ('recession_risk_score', models.FloatField(blank=True, null=True)),
                ('inflation_reacceleration_score', models.FloatField(blank=True, null=True)),
                ('financial_stress_score', models.FloatField(blank=True, null=True)),
                ('data_quality', models.FloatField(default=0.0)),
                ('source_freshness', models.JSONField(blank=True, default=dict)),
                ('feature_vector', models.JSONField(blank=True, default=dict)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(default='world_state_v1', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-as_of_date'],
                'indexes': [models.Index(fields=['-as_of_date'], name='macro_world_as_of_d_d3061f_idx'), models.Index(fields=['cadence', '-as_of_date'], name='macro_world_cadence_24fa46_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=32)),
                ('horizon', models.CharField(max_length=32)),
                ('validation_method', models.CharField(default='walk_forward', max_length=64)),
                ('sample_count', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['model_version', 'target', 'horizon'], name='macro_model_model_v_bf06ba_idx'), models.Index(fields=['-evaluated_at'], name='macro_model_evaluat_5f6a03_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('namespace', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=32)),
                ('horizon', models.CharField(max_length=32)),
                ('model_version', models.CharField(max_length=64)),
                ('feature_hash', models.CharField(max_length=64)),
                ('feature_vector', models.JSONField(blank=True, default=dict)),
                ('source_dates', models.JSONField(blank=True, default=dict)),
                ('data_quality', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
                'indexes': [models.Index(fields=['namespace', 'target', 'as_of_date'], name='macro_featu_namespa_b0796c_idx'), models.Index(fields=['model_version', 'as_of_date'], name='macro_featu_model_v_efad84_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='featuresnapshot',
            constraint=models.UniqueConstraint(fields=('as_of_date', 'namespace', 'target', 'horizon', 'model_version'), name='uq_feature_snapshot_identity'),
        ),
        migrations.AddIndex(
            model_name='dailypriceobservation',
            index=models.Index(fields=['ticker', 'observation_date'], name='macro_daily_ticker_2797b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailypriceobservation',
            index=models.Index(fields=['ticker', '-observation_date'], name='macro_daily_ticker_e2ef5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailypriceobservation',
            constraint=models.UniqueConstraint(fields=('ticker', 'observation_date'), name='uq_daily_price_ticker_date'),
        ),
    ]
