# Generated by Django 4.2.19 on 2026-05-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0019_dailypriceobservation_worldstatesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroConclusionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(unique=True)),
                ('previous_snapshot_date', models.DateField(blank=True, null=True)),
                ('current_view', models.TextField(blank=True)),
                ('previous_change', models.TextField(blank=True)),
                ('base_scenario_3m', models.TextField(blank=True)),
                ('upside_risk', models.TextField(blank=True)),
                ('downside_risk', models.TextField(blank=True)),
                ('watch_events', models.JSONField(blank=True, default=list)),
                ('model_reliability', models.TextField(blank=True)),
                ('driver_changes', models.JSONField(blank=True, default=list)),
                ('topic_mapping', models.JSONField(blank=True, default=list)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regime_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_conclusions', to='macro.regimesnapshot')),
            ],
            options={
                'ordering': ['-as_of_date'],
            },
        ),
        migrations.CreateModel(
            name='VintageObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('realtime_start', models.DateField()),
                ('realtime_end', models.DateField()),
                ('value', models.FloatField()),
                ('collected_at', models.DateTimeField()),
                ('source', models.CharField(default='fred', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vintage_observations', to='macro.indicator')),
            ],
            options={
                'ordering': ['indicator', 'observation_date', '-realtime_start'],
                'indexes': [models.Index(fields=['indicator', 'observation_date', '-realtime_start'], name='macro_vinta_indicat_f3bd8c_idx'), models.Index(fields=['indicator', 'realtime_start'], name='macro_vinta_indicat_ccfd32_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vintageobservation',
            constraint=models.UniqueConstraint(fields=('indicator', 'observation_date', 'realtime_start', 'realtime_end'), name='uq_vintage_indicator_date_realtime'),
        ),
        migrations.AddIndex(
            model_name='macroconclusionsnapshot',
            index=models.Index(fields=['-as_of_date'], name='macro_macro_as_of_d_22ed02_idx'),
        ),
    ]
