# Generated by Django 4.2.19 on 2026-06-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0022_policyexpectationsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('fred', 'FRED'), ('bls', 'BLS'), ('bea', 'BEA'), ('boj', 'BOJ'), ('esri', 'ESRI'), ('oecd', 'OECD'), ('yfinance', 'Yahoo Finance'), ('other', 'Other')], default='fred', max_length=32)),
                ('frequency', models.CharField(choices=[('daily', '日次'), ('weekly', '週次'), ('monthly', '月次'), ('quarterly', '四半期')], default='monthly', max_length=16)),
                ('category', models.CharField(choices=[('growth', '成長'), ('labor', '雇用・賃金'), ('inflation', '物価'), ('policy', '政策'), ('credit', '信用'), ('market', '市場'), ('global', '世界需要'), ('japan', '日本')], default='growth', max_length=32)),
                ('direction', models.IntegerField(default=1)),
                ('release_lag_days', models.IntegerField(default=0)),
                ('is_core', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_profile', to='macro.indicator')),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MacroForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(unique=True)),
                ('primary_regime', models.CharField(max_length=32)),
                ('previous_regime', models.CharField(blank=True, max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('data_quality_score', models.FloatField(default=0.0)),
                ('state_vector', models.JSONField(blank=True, default=dict)),
                ('regime_probabilities', models.JSONField(blank=True, default=dict)),
                ('risk_probabilities', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(default='macro_hatzius_v1', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macro_run', to='macro.forecastsnapshot')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='MacroScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('baseline', '基本'), ('upside', '上振れ'), ('downside', '下振れ')], max_length=32)),
                ('probability', models.FloatField()),
                ('growth_view', models.TextField()),
                ('inflation_view', models.TextField()),
                ('policy_view', models.TextField()),
                ('market_view', models.TextField()),
                ('nikkei_bias', models.CharField(choices=[('long', '上昇支援'), ('short', '下落圧力'), ('neutral', '中立')], default='neutral', max_length=16)),
                ('key_drivers', models.JSONField(blank=True, default=list)),
                ('invalidation_triggers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='macro.macroforecastrun')),
            ],
            options={
                'ordering': ['run', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MacroForecastOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('target_name', models.CharField(max_length=64)),
                ('predicted_value', models.FloatField(blank=True, null=True)),
                ('predicted_prob', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('brier_score', models.FloatField(blank=True, null=True)),
                ('absolute_error', models.FloatField(blank=True, null=True)),
                ('direction_hit', models.BooleanField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_outcomes', to='macro.forecastsnapshot')),
            ],
            options={
                'ordering': ['-target_date', '-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationVintage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('value', models.FloatField()),
                ('realtime_start', models.DateField()),
                ('realtime_end', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('source_revision_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vintages', to='macro.indicatorseries')),
            ],
            options={
                'ordering': ['series', 'observation_date', '-realtime_start'],
                'indexes': [models.Index(fields=['series', 'observation_date', '-realtime_start'], name='macro_obser_series__0ea21b_idx'), models.Index(fields=['series', 'realtime_start'], name='macro_obser_series__27fc25_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='observationvintage',
            constraint=models.UniqueConstraint(fields=('series', 'observation_date', 'realtime_start', 'realtime_end'), name='uq_series_observation_vintage'),
        ),
        migrations.AddIndex(
            model_name='macroscenario',
            index=models.Index(fields=['name', '-created_at'], name='macro_macro_name_e1b392_idx'),
        ),
        migrations.AddConstraint(
            model_name='macroscenario',
            constraint=models.UniqueConstraint(fields=('run', 'name'), name='uq_macro_scenario_run_name'),
        ),
        migrations.AddIndex(
            model_name='macroforecastrun',
            index=models.Index(fields=['-as_of'], name='macro_macro_as_of_cb6a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='macroforecastrun',
            index=models.Index(fields=['primary_regime', '-as_of'], name='macro_macro_primary_44d8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='macroforecastoutcome',
            index=models.Index(fields=['target_name', '-target_date'], name='macro_macro_target__f4749f_idx'),
        ),
        migrations.AddIndex(
            model_name='macroforecastoutcome',
            index=models.Index(fields=['forecast', 'target_name'], name='macro_macro_forecas_d1f5ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='macroforecastoutcome',
            constraint=models.UniqueConstraint(fields=('forecast', 'target_date', 'target_name'), name='uq_macro_forecast_outcome_target'),
        ),
        migrations.AddIndex(
            model_name='indicatorseries',
            index=models.Index(fields=['category', 'is_active'], name='macro_indic_categor_55c967_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorseries',
            index=models.Index(fields=['source', 'code'], name='macro_indic_source_fc7497_idx'),
        ),
    ]
