# Generated by Django 4.2.19 on 2026-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('market', models.CharField(max_length=16)),
                ('company', models.CharField(max_length=128)),
                ('industry', models.CharField(blank=True, max_length=64)),
                ('theme', models.CharField(blank=True, max_length=64)),
                ('watch_tier', models.CharField(blank=True, max_length=16)),
                ('watch_role', models.CharField(blank=True, max_length=64)),
                ('nikkei_weight', models.FloatField(blank=True, null=True)),
                ('peer_symbols', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='earning_sto_symbol_8ff8de_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('symbol', 'market'), name='earning_stock_symbol_market_uniq'),
        ),
    ]
