# Generated by Django 4.2.20 on 2025-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=100, unique=True, verbose_name='キャッシュキー')),
                ('data', models.JSONField(verbose_name='キャッシュデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
            ],
            options={
                'verbose_name': '決算データキャッシュ',
                'verbose_name_plural': '決算データキャッシュ',
                'db_table': 'earnings_data_cache',
            },
        ),
        migrations.CreateModel(
            name='EarningsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='決算発表日')),
                ('company', models.CharField(max_length=200, verbose_name='企業名')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='業種')),
                ('market', models.CharField(blank=True, max_length=50, verbose_name='市場')),
                ('symbol', models.CharField(blank=True, max_length=20, verbose_name='銘柄コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '決算発表予定',
                'verbose_name_plural': '決算発表予定',
                'db_table': 'earnings_announcements',
                'ordering': ['date', 'company'],
                'unique_together': {('date', 'company', 'symbol')},
            },
        ),
    ]
