# Generated by Django 4.2.19 on 2026-05-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_period', models.CharField(max_length=16)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('fundamental', models.CharField(choices=[('up', 'up'), ('flat', 'flat'), ('down', 'down')], default='flat', max_length=8)),
                ('direction', models.CharField(choices=[('up', 'up'), ('flat', 'flat'), ('down', 'down')], default='flat', max_length=8)),
                ('sentiment', models.CharField(choices=[('up', 'up'), ('flat', 'flat'), ('down', 'down')], default='flat', max_length=8)),
                ('risk_value', models.FloatField(blank=True, null=True)),
                ('eps_forecast', models.CharField(blank=True, max_length=32)),
                ('eps_4q_ago', models.CharField(blank=True, max_length=32)),
                ('eps_current', models.CharField(blank=True, max_length=32)),
                ('eps_4q_prior_period', models.CharField(blank=True, max_length=32)),
                ('surp_eps_4q_ago', models.CharField(blank=True, max_length=32)),
                ('surp_eps_current', models.CharField(blank=True, max_length=32)),
                ('surp_eps_4q_prior_period', models.CharField(blank=True, max_length=32)),
                ('sales_forecast', models.CharField(blank=True, max_length=32)),
                ('sales_4q_ago', models.CharField(blank=True, max_length=32)),
                ('sales_current', models.CharField(blank=True, max_length=32)),
                ('sales_4q_prior_period', models.CharField(blank=True, max_length=32)),
                ('surp_4q_ago', models.CharField(blank=True, max_length=32)),
                ('surp_current', models.CharField(blank=True, max_length=32)),
                ('surp_4q_prior_period', models.CharField(blank=True, max_length=32)),
                ('theme_score', models.FloatField(blank=True, null=True)),
                ('gross_margin', models.FloatField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('relative_strength', models.FloatField(blank=True, null=True)),
                ('guidance_revision', models.CharField(blank=True, choices=[('', '—'), ('up', 'up'), ('flat', 'flat'), ('down', 'down')], default='', max_length=8)),
                ('reaction_close', models.FloatField(blank=True, null=True)),
                ('reaction_next_day', models.FloatField(blank=True, null=True)),
                ('market_interpretation', models.CharField(blank=True, choices=[('', '—'), ('bullish', 'bullish'), ('neutral', 'neutral'), ('bearish', 'bearish')], default='', max_length=16)),
                ('past_reactions', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='earning.stock')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['event_date'], name='earning_ear_event_d_77f4bd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.UniqueConstraint(fields=('stock', 'fiscal_period'), name='earning_event_stock_period_uniq'),
        ),
    ]
