# Generated by Django 4.2.19 on 2026-05-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0002_earningsevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_reaction', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='earning.earningsevent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='earningsprediction',
            constraint=models.UniqueConstraint(fields=('event', 'model_version'), name='earning_prediction_event_model_uniq'),
        ),
    ]
