# Generated by Django 4.2.19 on 2026-05-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0003_earningsprediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsPriceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('offset_days', models.IntegerField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_window', to='earning.earningsevent')),
            ],
            options={
                'ordering': ['event', 'trade_date'],
                'indexes': [models.Index(fields=['event', 'offset_days'], name='earning_ear_event_i_c0baa5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='earningspricewindow',
            constraint=models.UniqueConstraint(fields=('event', 'trade_date'), name='earning_price_window_event_date_uniq'),
        ),
    ]
