# Generated by Django 4.2.19 on 2026-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0004_earningspricewindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsevent',
            name='hy_spread_at_event',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='rut_at_event',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='skew_at_event',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='t5yie_at_event',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='vix_at_event',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
