# Generated by Django 4.2.19 on 2026-05-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0005_earningsevent_hy_spread_at_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsevent',
            name='eps_4q_ago',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='eps_4q_prior_period',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='eps_current',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='sales_4q_ago',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='sales_4q_prior_period',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='sales_current',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='surp_4q_ago',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='surp_4q_prior_period',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='surp_eps_4q_ago',
        ),
        migrations.RemoveField(
            model_name='earningsevent',
            name='surp_eps_4q_prior_period',
        ),
    ]
